"""second migration

Revision ID: e266d86d280e
Revises: c6fac62ffa69
Create Date: 2024-09-18 22:55:44.848325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e266d86d280e'
down_revision: Union[str, None] = 'c6fac62ffa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('weather_in_city', sa.JSON(), nullable=True))
    op.drop_column('weather_data', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('weather_data', 'weather_in_city')
    # ### end Alembic commands ###
